services:
  db:
    image: postgres:latest
    container_name: nestjs-project
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
